# Generated by Django 4.0.6 on 2022-07-23 04:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BillingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_id",
                    models.CharField(
                        blank=True, default=uuid.uuid4, max_length=36, unique=True
                    ),
                ),
                ("active", models.BooleanField()),
                ("amount", models.IntegerField()),
                (
                    "amount_decimal",
                    models.DecimalField(decimal_places=2, max_digits=11),
                ),
                ("billing_scheme", models.CharField(max_length=30)),
                ("time_created", models.TimeField()),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("week", "Week"),
                            ("month", "Month"),
                            ("year", "Year"),
                        ],
                        default="month",
                        max_length=5,
                    ),
                ),
                ("interval_count", models.IntegerField()),
                ("nickname", models.CharField(max_length=30)),
                ("product", models.CharField(max_length=30)),
                ("tiers_mode", models.CharField(max_length=30)),
                ("trial_period_days", models.IntegerField()),
                (
                    "usage_type",
                    models.CharField(
                        choices=[("LI", "Licensed"), ("ME", "Metered")],
                        default="ME",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "billing_id",
                    models.CharField(
                        blank=True, default=uuid.uuid4, max_length=100, unique=True
                    ),
                ),
                ("system_id", models.CharField(max_length=100, unique=True)),
                ("email_address", models.CharField(max_length=30)),
                ("phone_number", models.CharField(max_length=30)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("default_payment_source", models.CharField(max_length=60)),
                ("invoice_prefix", models.CharField(max_length=30)),
                ("next_invoice_sequence", models.CharField(max_length=30)),
                ("tax_exempt", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=200)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.customer",
                    ),
                ),
            ],
        ),
    ]
