# Generated by Django 4.1 on 2022-08-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="company_name",
        ),
        migrations.AddField(
            model_name="customer",
            name="payment_provider_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(default="pending", max_length=10),
        ),
    ]
