# Generated by Django 4.0.6 on 2022-07-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_alter_customer_billing_configuration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="external_id",
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_id",
            field=models.CharField(default=" ", max_length=40, unique=True),
        ),
    ]
