# Generated by Django 4.0.6 on 2022-07-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing",
            "0003_remove_billingplan_active_remove_billingplan_amount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="billing_id",
            field=models.CharField(default=" ", max_length=40),
        ),
        migrations.AddField(
            model_name="customer",
            name="external_id",
            field=models.CharField(default=" ", max_length=40),
        ),
    ]
