# Generated by Django 4.0.5 on 2022-08-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_rename_base_rate_billingplan_flat_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("start_date", "end_date")},
        ),
    ]
