# Generated by Django 4.0.6 on 2022-07-24 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_customer_billing_id_customer_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="billing_id",
            field=models.CharField(default=uuid.uuid4, max_length=40),
        ),
    ]
