# Generated by Django 4.0.5 on 2022-08-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='billing_configuration',
        ),
    ]
