# Generated by Django 4.0.6 on 2022-07-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_billablemetric_remove_billingplan_billable_metrics_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billingplan",
            old_name="billing_id",
            new_name="plan_id",
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
