# Generated by Django 4.0.6 on 2022-07-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_alter_customer_billing_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["idempotency_id"]},
        ),
        migrations.AddField(
            model_name="event",
            name="idempotency_id",
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
