# Generated by Django 4.0.6 on 2022-07-28 00:51

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_rename_billing_id_billingplan_plan_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="billable_metric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="billing.billablemetric",
            ),
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="description",
            field=models.CharField(blank=True, default=" ", max_length=256),
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="metric_amount",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=10,
                default_currency="USD",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="starter_metric_quatity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
