# Generated by Django 4.0.6 on 2022-07-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_subscription_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="last_name",
        ),
        migrations.AddField(
            model_name="customer",
            name="name",
            field=models.CharField(default=" ", max_length=100),
            preserve_default=False,
        ),
    ]
