# Generated by Django 4.0.6 on 2022-07-28 22:17

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_alter_subscription_start_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="time_created",
            new_name="issue_date",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="due_date",
        ),
        migrations.AddField(
            model_name="invoice",
            name="customer_billing_id",
            field=models.CharField(default=3, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="customer_name",
            field=models.CharField(default="jeff", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_pdf",
            field=models.FileField(blank=True, null=True, upload_to="invoices/"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="line_items",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, max_length=36, primary_key=True, serialize=False
            ),
        ),
    ]
