# Generated by Django 4.0.6 on 2022-07-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_rename_time_created_invoice_issue_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(),
        ),
    ]
