# Generated by Django 4.1 on 2022-08-04 17:08

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0002_alter_tenant_stripe_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="stripe_api_key",
            field=django_cryptography.fields.encrypt(
                models.CharField(blank=True, default="", max_length=110)
            ),
        ),
    ]
