# Generated by Django 4.0.5 on 2022-08-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0003_alter_tenant_stripe_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="stripe_api_key",
            field=models.CharField(blank=True, default="", max_length=110),
        ),
    ]
