# Generated by Django 4.0.5 on 2022-09-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0007_alter_customer_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="billablemetric",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="billablemetric",
            constraint=models.UniqueConstraint(
                fields=(
                    "organization",
                    "event_name",
                    "aggregation_type",
                    "property_name",
                ),
                name="unique_with_property_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="billablemetric",
            constraint=models.UniqueConstraint(
                condition=models.Q(("property_name", None)),
                fields=("organization", "event_name", "aggregation_type"),
                name="unique_without_property_name",
            ),
        ),
    ]
