# Generated by Django 4.0.5 on 2022-09-21 06:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0015_billablemetric_metric_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="billablemetric",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="billablemetric",
            name="billable_metric_name",
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="billablemetric",
            unique_together={("organization", "billable_metric_name")},
        ),
        migrations.RemoveField(
            model_name="billablemetric",
            name="metric_name",
        ),
    ]
