# Generated by Django 4.0.5 on 2022-10-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "metering_billing",
            "0032_rename_subscription_uid_subscription_subscription_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plancomponent",
            name="cost_per_batch_currency",
        ),
        migrations.AlterField(
            model_name="plancomponent",
            name="cost_per_batch",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
    ]
