# Generated by Django 4.0.5 on 2022-11-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0066_change_unique_rate_to_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalinvoice",
            name="external_payment_obj",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="external_payment_obj",
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="customer",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="organization",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="subscription",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="organization",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="subscription",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
