# Generated by Django 4.0.5 on 2022-11-10 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "metering_billing",
            "0067_remove_historicalinvoice_external_payment_obj_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalinvoice",
            old_name="customer",
            new_name="old_customer",
        ),
        migrations.RenameField(
            model_name="historicalinvoice",
            old_name="organization",
            new_name="old_organization",
        ),
        migrations.RenameField(
            model_name="historicalinvoice",
            old_name="subscription",
            new_name="old_subscription",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="customer",
            new_name="old_customer",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="organization",
            new_name="old_organization",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="subscription",
            new_name="old_subscription",
        ),
    ]
