# Generated by Django 4.0.5 on 2022-11-11 00:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0070_auto_20221110_2351"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalinvoice",
            name="old_customer",
        ),
        migrations.RemoveField(
            model_name="historicalinvoice",
            name="old_organization",
        ),
        migrations.RemoveField(
            model_name="historicalinvoice",
            name="old_subscription",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="old_customer",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="old_organization",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="old_subscription",
        ),
    ]
