# Generated by Django 4.0.5 on 2022-11-14 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0072_customer_payment_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="cust_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="metering_billing.customer",
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("voided", "Voided"),
                    ("paid", "Paid"),
                    ("unpaid", "Unpaid"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("voided", "Voided"),
                    ("paid", "Paid"),
                    ("unpaid", "Unpaid"),
                ],
                max_length=40,
            ),
        ),
    ]
