# Generated by Django 4.0.5 on 2022-11-15 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0074_historicalplanversion_transition_to_and_more"),
        ("metering_billing", "0075_alter_pricetier_batch_rounding_type_and_more"),
    ]

    operations = []
