# Generated by Django 4.0.5 on 2022-11-22 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "metering_billing",
            "0081_remove_customerbalanceadjustment_amount_currency_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="default_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="metering_billing.pricingunit",
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="default_currency",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="metering_billing.pricingunit",
            ),
        ),
        migrations.AddField(
            model_name="historicalorganization",
            name="default_currency",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="metering_billing.pricingunit",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="default_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="metering_billing.pricingunit",
            ),
        ),
        migrations.AddField(
            model_name="plancomponent",
            name="pricing_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="metering_billing.pricingunit",
            ),
        ),
        migrations.CreateModel(
            name="CustomPricingUnitConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_qty", models.DecimalField(decimal_places=10, max_digits=20)),
                ("to_qty", models.DecimalField(decimal_places=10, max_digits=20)),
                (
                    "from_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="metering_billing.pricingunit",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_unit_conversions",
                        to="metering_billing.planversion",
                    ),
                ),
                (
                    "to_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="metering_billing.pricingunit",
                    ),
                ),
            ],
        ),
    ]
