# Generated by Django 4.0.5 on 2022-11-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0085_merge_20221127_1948"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicelineitem",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=10, default=1.0, max_digits=20, null=True
            ),
        ),
    ]
