# Generated by Django 4.0.5 on 2022-12-14 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0119_accountsreceivabledebtor_and_more"),
        ("metering_billing", "0119_alter_customer_customer_id_and_more"),
    ]

    operations = []
