# Generated by Django 4.0.5 on 2022-12-15 22:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0125_delete_historicalsubscription"),
        ("metering_billing", "0127_pricingunit_custom"),
    ]

    operations = []
