# Generated by Django 4.0.5 on 2023-01-14 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0154_fill_uuids"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="planversion",
            name="unique_version_id",
        ),
        migrations.RemoveConstraint(
            model_name="subscription",
            name="unique_subscription_id",
        ),
        migrations.RemoveConstraint(
            model_name="subscriptionrecord",
            name="unique_subscription_record_id",
        ),
        migrations.RemoveConstraint(
            model_name="usagealert",
            name="unique_alert_id_per_org",
        ),
        migrations.RemoveConstraint(
            model_name="metric",
            name="unique_org_metric_id",
        ),
        migrations.RemoveField(
            model_name="backtest",
            name="backtest_id_old",
        ),
        migrations.RemoveField(
            model_name="customerbalanceadjustment",
            name="adjustment_id_old",
        ),
        migrations.RemoveField(
            model_name="historicalbacktest",
            name="backtest_id_old",
        ),
        migrations.RemoveField(
            model_name="historicalmetric",
            name="metric_id_old",
        ),
        migrations.RemoveField(
            model_name="historicalorganization",
            name="organization_id_old",
        ),
        migrations.RemoveField(
            model_name="historicalorganizationsetting",
            name="setting_id_old",
        ),
        migrations.RemoveField(
            model_name="historicalplan",
            name="plan_id_old",
        ),
        migrations.RemoveField(
            model_name="historicalplanversion",
            name="version_id_old",
        ),
        migrations.RemoveField(
            model_name="historicalsubscriptionrecord",
            name="subscription_record_id_old",
        ),
        migrations.RemoveField(
            model_name="metric",
            name="metric_id_old",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="organization_id_old",
        ),
        migrations.RemoveField(
            model_name="organizationsetting",
            name="setting_id_old",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="plan_id_old",
        ),
        migrations.RemoveField(
            model_name="planversion",
            name="version_id_old",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="subscription_id_old",
        ),
        migrations.RemoveField(
            model_name="subscriptionrecord",
            name="subscription_record_id_old",
        ),
        migrations.RemoveField(
            model_name="usagealert",
            name="usage_alert_id_old",
        ),
        migrations.RemoveField(
            model_name="webhookendpoint",
            name="webhook_endpoint_id_old",
        ),
        migrations.RemoveField(
            model_name="webhookendpoint",
            name="webhook_secret_old",
        ),
    ]
