# Generated by Django 4.0.5 on 2023-02-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0171_remove_subscription_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubscriptionrecord",
            name="unadjusted_duration_microseconds",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="The duration of the subscription in microseconds without any anchoring.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrecord",
            name="unadjusted_duration_microseconds",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="The duration of the subscription in microseconds without any anchoring.",
                null=True,
            ),
        ),
    ]
