# Generated by Django 4.0.5 on 2023-02-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0177_customer_timezone_customer_timezone_set_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_id"),
                name="unique_idempotency_id_per_org",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="event",
            unique_together=set(),
        ),
    ]
