# Generated by Django 4.0.5 on 2022-08-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="stripe_api_key",
            new_name="stripe_id",
        ),
    ]
