# Generated by Django 4.0.5 on 2022-08-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
