# Generated by Django 4.0.5 on 2022-08-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0002_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('customer', 'billing_plan', 'start_date', 'end_date')},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('fulfilled', 'Fullfilled'), ('not_sent', 'Not Sent')], default='not_sent', max_length=10),
        ),
    ]
