# Generated by Django 4.0.5 on 2022-08-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0002_remove_organization_users_remove_user_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='stripe_api_key',
        ),
    ]
