# Generated by Django 4.0.5 on 2022-08-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0002_subscription_is_new'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billablemetric',
            unique_together={('organization', 'event_name', 'property_name', 'aggregation_type')},
        ),
    ]
