# Generated by Django 4.0.5 on 2022-09-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "metering_billing",
            "0003_alter_invoice_customer_alter_invoice_line_items_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("requires_payment_method", "Requires Payment Method"),
                    ("requires_action", "Requires Action"),
                    ("processing", "Processing"),
                    ("succeeded", "Succeeded"),
                    ("not_connected_to_stripe", "Not Connected to Stripe"),
                ],
                max_length=35,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
