# Generated by Django 4.0.5 on 2022-09-04 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0003_invoice_cost_due_currency_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='exclude_overlapping_subscriptions',
        ),
    ]
