# Generated by Django 4.0.5 on 2022-08-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0003_remove_organization_stripe_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stripe_api_key',
            field=models.CharField(blank=True, default='', max_length=110),
        ),
    ]
