# Generated by Django 4.0.5 on 2022-08-30 00:07

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import metering_billing.models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0003_alter_subscription_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_billing_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_plan', to='metering_billing.billingplan'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('fulfilled', 'Fullfilled'), ('not_sent', 'Not Sent')], default='not_sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_plan', to='metering_billing.billingplan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('not_started', 'Not Started')], default='not_started', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('cancelled', False)), expressions=((metering_billing.models.TsTzRange('start_date', 'end_date', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('organization', '='), ('customer', '='), ('billing_plan', '=')), name='exclude_overlapping_subscriptions'),
        ),
    ]
