# Generated by Django 4.0.5 on 2022-09-01 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0002_remove_organization_users_remove_user_company_name_and_more'),
        ('metering_billing', '0003_alter_billablemetric_unique_together'),
    ]

    operations = [
    ]
