# Generated by Django 4.0.5 on 2022-08-17 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "metering_billing",
            "0003_remove_invoice_cost_due_currency_invoice_customer_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apitoken",
            options={
                "ordering": ("-created",),
                "verbose_name": "API Token",
                "verbose_name_plural": "API Tokens",
            },
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="metering_billing.organization",
            ),
        ),
    ]
