# Generated by Django 4.0.5 on 2022-08-15 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0004_organization_stripe_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.CharField(default=uuid.UUID('e35e52e7-e56c-4df5-83c4-f49b3ede6e25'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
