# Generated by Django 4.0.5 on 2022-09-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "metering_billing",
            "0004_remove_subscription_exclude_overlapping_subscriptions",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(),
        ),
    ]
