# Generated by Django 4.0.5 on 2022-08-20 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0004_alter_apitoken_options_alter_apitoken_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['time_created', 'idempotency_id']},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='created_on',
        ),
        migrations.AddField(
            model_name='organization',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='billablemetric',
            name='property_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='stripe_id',
            field=models.CharField(blank=True, default='', max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
