# Generated by Django 4.0.5 on 2022-08-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0004_alter_apitoken_options_alter_apitoken_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="properties",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
