# Generated by Django 4.0.5 on 2022-09-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0005_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancomponent',
            name='metric_amount_per_cost',
            field=models.DecimalField(decimal_places=10, default=1.0, max_digits=20),
        ),
    ]
