# Generated by Django 4.0.5 on 2022-09-06 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0003_alter_billingplan_components"),
        ("metering_billing", "0005_invoice_payment_intent_id"),
    ]

    operations = []
