# Generated by Django 4.0.5 on 2022-08-15 08:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0007_alter_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.CharField(default=uuid.UUID('eaf0325b-5ffc-4cb8-9942-eace9ac54504'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
