# Generated by Django 4.0.5 on 2022-09-08 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0008_alter_billablemetric_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="next_plan",
        ),
        migrations.AddField(
            model_name="billingplan",
            name="billing_plan_id",
            field=models.CharField(default="existing", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subscription",
            name="billing_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="metering_billing.billingplan",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="billingplan",
            unique_together={("organization", "billing_plan_id")},
        ),
    ]
