# Generated by Django 4.0.5 on 2022-08-15 08:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0008_alter_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.CharField(default=uuid.UUID('1309e591-d6b0-4e38-b10d-7d3a492b64b1'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
