# Generated by Django 4.0.5 on 2022-08-15 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0010_alter_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.CharField(default=uuid.UUID('976f3d1e-b2c1-49fb-8bb2-c8f29f8e8e59'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
