# Generated by Django 4.0.5 on 2022-08-15 08:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0011_alter_invoice_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apitoken',
            options={'ordering': ('-created',), 'verbose_name': 'API Token', 'verbose_name_plural': 'API Tokens'},
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='metering_billing.organization'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.CharField(default=uuid.UUID('f5d74ef7-f7d9-43dd-bfb4-2a91d45ef212'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
