# Generated by Django 4.0.5 on 2022-08-15 09:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0012_alter_apitoken_options_alter_apitoken_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.CharField(default=uuid.UUID('8e6d2b84-6f3d-40da-b64f-b3e4ead7d193'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default=uuid.UUID('49f69f5d-81e2-49db-9d0c-01e6416ab4ee'), max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
