# Generated by Django 4.0.5 on 2022-09-26 21:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0018_alter_subscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="subscription_uid",
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("organization", "subscription_uid")},
        ),
    ]
