# Generated by Django 4.0.5 on 2022-09-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0024_alter_billingplan_components_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="components",
            field=models.ManyToManyField(to="metering_billing.plancomponent"),
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="features",
            field=models.ManyToManyField(to="metering_billing.feature"),
        ),
    ]
