/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LotusApi } from "../../../..";
import * as core from "../../../../core";

export const Address: core.serialization.ObjectSchema<
  serializers.Address.Raw,
  LotusApi.Address
> = core.serialization.object({
  city: core.serialization.string(),
  country: core.serialization.string(),
  line1: core.serialization.string(),
  line2: core.serialization.string().optional(),
  postalCode: core.serialization.property(
    "postal_code",
    core.serialization.string()
  ),
  state: core.serialization.string(),
});

export declare namespace Address {
  interface Raw {
    city: string;
    country: string;
    line1: string;
    line2?: string | null;
    postal_code: string;
    state: string;
  }
}
