/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LotusApi } from "../../../..";
import * as core from "../../../../core";

export const CustomerIntegrations: core.serialization.ObjectSchema<
  serializers.CustomerIntegrations.Raw,
  LotusApi.CustomerIntegrations
> = core.serialization.object({
  stripe: core.serialization
    .lazyObject(
      async () => (await import("../../..")).CustomerStripeIntegration
    )
    .optional(),
});

export declare namespace CustomerIntegrations {
  interface Raw {
    stripe?: serializers.CustomerStripeIntegration.Raw | null;
  }
}
