/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LotusApi } from "../../../..";
import * as core from "../../../../core";

export const LightweightPlanVersion: core.serialization.ObjectSchema<
  serializers.LightweightPlanVersion.Raw,
  LotusApi.LightweightPlanVersion
> = core.serialization.object({
  planName: core.serialization.property(
    "plan_name",
    core.serialization.string()
  ),
  planId: core.serialization.property("plan_id", core.serialization.string()),
  version: core.serialization.number(),
  versionId: core.serialization.property(
    "version_id",
    core.serialization.string()
  ),
});

export declare namespace LightweightPlanVersion {
  interface Raw {
    plan_name: string;
    plan_id: string;
    version: number;
    version_id: string;
  }
}
