/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LotusApi } from "../../../..";
import * as core from "../../../../core";

export const PaymentProvider: core.serialization.Schema<
  serializers.PaymentProvider.Raw,
  LotusApi.PaymentProvider
> = core.serialization.enum_(["stripe"]);

export declare namespace PaymentProvider {
  type Raw = "stripe";
}
