# Generated by Django 4.0.5 on 2022-09-05 05:45

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="flat_rate",
            field=djmoney.models.fields.MoneyField(
                decimal_places=10, default_currency="USD", max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="interval",
            field=models.CharField(
                choices=[("week", "Week"), ("month", "Month"), ("year", "Year")],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="pay_in_advance",
            field=models.BooleanField(),
        ),
    ]
