# Generated by Django 4.0.5 on 2022-09-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "metering_billing",
            "0013_billablemetric_recurring_plancomponent_max_amount_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="billablemetric",
            old_name="recurring",
            new_name="carries_over",
        ),
        migrations.AddField(
            model_name="billablemetric",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("aggregation", "Aggregatable"),
                    ("stateful", "State Logging"),
                ],
                default="aggregation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="billablemetric",
            name="stateful_freq_num",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="billablemetric",
            name="stateful_freq_unit",
            field=models.CharField(
                blank=True, choices=[("day", "Day")], max_length=20, null=True
            ),
        ),
    ]
