# Generated by Django 4.0.5 on 2022-09-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0017_alter_invoice_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("ended", "Ended"),
                    ("not_started", "Not Started"),
                    ("canceled", "Canceled"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
