# Generated by Django 4.0.5 on 2022-09-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "metering_billing",
            "0023_remove_billablemetric_unique_with_property_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="components",
            field=models.ManyToManyField(
                blank=True, null=True, to="metering_billing.plancomponent"
            ),
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="features",
            field=models.ManyToManyField(
                blank=True, null=True, to="metering_billing.feature"
            ),
        ),
    ]
