# Generated by Django 4.0.5 on 2022-10-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0026_alter_user_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="payment_intent_id",
            new_name="external_payment_obj_id",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="status",
        ),
        migrations.AddField(
            model_name="customer",
            name="payment_provider",
            field=models.CharField(
                blank=True, choices=[("stripe", "Stripe")], max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="cust_connected_to_payment_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="org_connected_to_cust_payment_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("paid", "Paid"), ("unpaid", "Unpaid")],
                default="unpaid",
                max_length=40,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="payment_provider_ids",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
