# Generated by Django 4.0.5 on 2022-10-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0028_billingplan_replacement_billing_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="flat_fee_already_billed",
            field=models.DecimalField(
                blank=True, decimal_places=10, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="prorated_flat_costs_dict",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
