# Generated by Django 4.0.5 on 2022-10-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0029_subscription_flat_fee_already_billed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
