# Generated by Django 4.0.5 on 2022-10-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "metering_billing",
            "0033_remove_plancomponent_cost_per_batch_currency_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billingplan",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="currency",
        ),
        migrations.AddField(
            model_name="invoice",
            name="external_payment_obj_type",
            field=models.CharField(
                blank=True, choices=[("stripe", "Stripe")], max_length=40, null=True
            ),
        ),
    ]
