# Generated by Django 4.0.5 on 2022-10-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0039_alter_historicalalert_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="payment_provider",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="payment_provider_id",
        ),
        migrations.RemoveField(
            model_name="historicalcustomer",
            name="payment_provider",
        ),
        migrations.RemoveField(
            model_name="historicalcustomer",
            name="payment_provider_id",
        ),
        migrations.AddField(
            model_name="customer",
            name="payment_provider_ids",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="payment_provider_ids",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
