# Generated by Django 4.0.5 on 2022-10-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0040_remove_customer_payment_provider_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="payment_provider_ids",
            new_name="payment_providers",
        ),
        migrations.RenameField(
            model_name="historicalcustomer",
            old_name="payment_provider_ids",
            new_name="payment_providers",
        ),
        migrations.AddField(
            model_name="customer",
            name="sources",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="sources",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcustomer",
            name="customer_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
