# Generated by Django 4.0.5 on 2022-10-13 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0042_backtest_remove_customer_billing_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_alerts",
                to="metering_billing.organization",
            ),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_api_keys",
                to="metering_billing.organization",
            ),
        ),
        migrations.AlterField(
            model_name="backtest",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_backtests",
                to="metering_billing.organization",
            ),
        ),
        migrations.AlterField(
            model_name="backtestsubstitution",
            name="backtest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backtest_substitutions",
                to="metering_billing.backtest",
            ),
        ),
        migrations.AlterField(
            model_name="billablemetric",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_billable_metrics",
                to="metering_billing.organization",
            ),
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_billing_plans",
                to="metering_billing.organization",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_customers",
                to="metering_billing.organization",
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_features",
                to="metering_billing.organization",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="billing_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bp_subscriptions",
                to="metering_billing.billingplan",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_subscriptions",
                to="metering_billing.customer",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_subscriptions",
                to="metering_billing.organization",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_users",
                to="metering_billing.organization",
            ),
        ),
    ]
