# Generated by Django 4.0.5 on 2022-10-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "metering_billing",
            "0043_alter_alert_organization_alter_apitoken_organization_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="billingplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("deleted", "Deleted"),
                    ("experimental", "Experimental"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalbillingplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("deleted", "Deleted"),
                    ("experimental", "Experimental"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="billingplan",
            name="interval",
            field=models.CharField(
                choices=[("week", "Week"), ("month", "Month"), ("year", "Year")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbillingplan",
            name="interval",
            field=models.CharField(
                choices=[("week", "Week"), ("month", "Month"), ("year", "Year")],
                max_length=10,
            ),
        ),
    ]
