# Generated by Django 4.0.5 on 2022-10-13 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "metering_billing",
            "0044_billingplan_status_historicalbillingplan_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("experimental", "Experimental"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbillingplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("experimental", "Experimental"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubscription",
            name="billing_plan",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="bp_subscription",
                to="metering_billing.billingplan",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="billing_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bp_subscriptions",
                related_query_name="bp_subscription",
                to="metering_billing.billingplan",
            ),
        ),
    ]
