# Generated by Django 4.0.5 on 2022-10-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0047_organizationinvitetoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationinvitetoken",
            name="is_valid",
        ),
        migrations.AddField(
            model_name="organizationinvitetoken",
            name="email",
            field=models.EmailField(default="test@email.com", max_length=254),
            preserve_default=False,
        ),
    ]
