# Generated by Django 4.0.5 on 2022-11-01 19:57

from django.db import migrations, models
import metering_billing.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0058_remove_customer_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinvoice",
            name="invoice_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=metering_billing.utils.utils.invoice_uuid,
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_id",
            field=models.CharField(
                blank=True,
                default=metering_billing.utils.utils.invoice_uuid,
                max_length=100,
                unique=True,
            ),
        ),
    ]
