# Generated by Django 4.0.5 on 2022-10-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0058_historicalinvoice_invoice_id_invoice_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalplanversion",
            name="usage_billing_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("yearly", "Yearly"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="planversion",
            name="usage_billing_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("yearly", "Yearly"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
