# Generated by Django 4.0.5 on 2022-11-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0062_alter_backtest_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plancomponent",
            name="free_metric_units",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
    ]
