# Generated by Django 4.0.5 on 2022-11-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0063_alter_plancomponent_free_metric_units'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='billablemetric',
            name='unique_with_property_name',
        ),
        migrations.RemoveConstraint(
            model_name='billablemetric',
            name='unique_without_property_name',
        ),
        migrations.RemoveField(
            model_name='billablemetric',
            name='aggregation_type',
        ),
        migrations.RemoveField(
            model_name='historicalbillablemetric',
            name='aggregation_type',
        ),
        migrations.RemoveField(
            model_name='historicalplanversion',
            name='proration_granularity',
        ),
        migrations.RemoveField(
            model_name='planversion',
            name='proration_granularity',
        ),
        migrations.AddField(
            model_name='billablemetric',
            name='billable_aggregation_type',
            field=models.CharField(blank=True, choices=[('count', 'Count'), ('sum', 'Sum'), ('max', 'Max'), ('unique', 'Unique'), ('latest', 'Latest'), ('average', 'Average')], default='sum', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='billablemetric',
            name='event_type',
            field=models.CharField(blank=True, choices=[('delta', 'Delta'), ('total', 'Total')], default='total', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='billablemetric',
            name='granularity',
            field=models.CharField(blank=True, choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('quarter', 'Quarter'), ('total', 'Total')], default='total', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='billablemetric',
            name='usage_aggregation_type',
            field=models.CharField(choices=[('count', 'Count'), ('sum', 'Sum'), ('max', 'Max'), ('unique', 'Unique'), ('latest', 'Latest'), ('average', 'Average')], default='count', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalbillablemetric',
            name='billable_aggregation_type',
            field=models.CharField(blank=True, choices=[('count', 'Count'), ('sum', 'Sum'), ('max', 'Max'), ('unique', 'Unique'), ('latest', 'Latest'), ('average', 'Average')], default='sum', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalbillablemetric',
            name='event_type',
            field=models.CharField(blank=True, choices=[('delta', 'Delta'), ('total', 'Total')], default='total', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalbillablemetric',
            name='granularity',
            field=models.CharField(blank=True, choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('quarter', 'Quarter'), ('total', 'Total')], default='total', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalbillablemetric',
            name='usage_aggregation_type',
            field=models.CharField(choices=[('count', 'Count'), ('sum', 'Sum'), ('max', 'Max'), ('unique', 'Unique'), ('latest', 'Latest'), ('average', 'Average')], default='count', max_length=10),
        ),
        migrations.AlterField(
            model_name='billablemetric',
            name='metric_type',
            field=models.CharField(choices=[('counter', 'Counter'), ('stateful', 'State Logging'), ('rate', 'Rate')], default='counter', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalbillablemetric',
            name='metric_type',
            field=models.CharField(choices=[('counter', 'Counter'), ('stateful', 'State Logging'), ('rate', 'Rate')], default='counter', max_length=20),
        ),
    ]
