# Generated by Django 4.0.5 on 2022-11-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0066_change_unique_rate_to_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalinvoice",
            old_name="customer",
            new_name="old_customer",
        ),
        migrations.RenameField(
            model_name="historicalinvoice",
            old_name="organization",
            new_name="old_organization",
        ),
        migrations.RenameField(
            model_name="historicalinvoice",
            old_name="subscription",
            new_name="old_subscription",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="customer",
            new_name="old_customer",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="organization",
            new_name="old_organization",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="subscription",
            new_name="old_subscription",
        ),
        migrations.RemoveField(
            model_name="historicalinvoice",
            name="external_payment_obj",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="external_payment_obj",
        ),
    ]
