# Generated by Django 4.0.5 on 2022-11-10 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "metering_billing",
            "0068_rename_customer_historicalinvoice_old_customer_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvoice",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="metering_billing.customer",
            ),
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="metering_billing.organization",
            ),
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="metering_billing.subscription",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="metering_billing.customer",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="metering_billing.organization",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="metering_billing.subscription",
            ),
        ),
    ]
