# Generated by Django 4.0.5 on 2022-11-17 23:54

from django.db import migrations, models

import metering_billing.utils.utils


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0077_remove_plancomponent_cost_per_batch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorganization",
            name="organization_id",
            field=models.CharField(
                default=metering_billing.utils.utils.organization_uuid, max_length=100
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="organization_id",
            field=models.CharField(
                default=metering_billing.utils.utils.organization_uuid, max_length=100
            ),
        ),
    ]
