# Generated by Django 4.0.5 on 2022-11-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0078_historicalorganization_organization_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="idempotency_id",
            field=models.CharField(max_length=255),
        ),
    ]
