# Generated by Django 4.0.5 on 2022-11-22 19:02

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0080_historicalmetric_is_cost_metric_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerbalanceadjustment",
            name="amount_currency",
        ),
        migrations.RemoveField(
            model_name="historicalinvoice",
            name="cost_due_currency",
        ),
        migrations.RemoveField(
            model_name="historicalplanversion",
            name="flat_rate_currency",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="cost_due_currency",
        ),
        migrations.RemoveField(
            model_name="invoicelineitem",
            name="subtotal_currency",
        ),
        migrations.RemoveField(
            model_name="planversion",
            name="flat_rate_currency",
        ),
        migrations.AlterField(
            model_name="customerbalanceadjustment",
            name="amount",
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="cost_due",
            field=models.DecimalField(
                decimal_places=10, default=Decimal("0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="historicalplanversion",
            name="flat_rate",
            field=models.DecimalField(
                decimal_places=10, default=Decimal("0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="cost_due",
            field=models.DecimalField(
                decimal_places=10, default=Decimal("0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=10, default=Decimal("0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="planversion",
            name="flat_rate",
            field=models.DecimalField(
                decimal_places=10, default=Decimal("0"), max_digits=20
            ),
        ),
        migrations.CreateModel(
            name="PricingUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metering_billing.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customerbalanceadjustment",
            name="pricing_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="metering_billing.pricingunit",
            ),
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="pricing_unit",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="metering_billing.pricingunit",
            ),
        ),
        migrations.AddField(
            model_name="historicalplanversion",
            name="pricing_unit",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="metering_billing.pricingunit",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="pricing_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="metering_billing.pricingunit",
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="pricing_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="metering_billing.pricingunit",
            ),
        ),
        migrations.AddField(
            model_name="planversion",
            name="pricing_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="metering_billing.pricingunit",
            ),
        ),
    ]
