# Generated by Django 4.0.5 on 2022-11-27 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0079_alter_event_idempotency_id"),
        ("metering_billing", "0081_remove_historicalinvoice_line_items_and_more"),
    ]

    operations = []
