# Generated by Django 4.0.5 on 2022-11-24 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0081_plancomponent_separate_by"),
        ("metering_billing", "0081_remove_historicalinvoice_line_items_and_more"),
    ]

    operations = []
