# Generated by Django 4.0.5 on 2022-11-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0082_merge_20221124_0458"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicelineitem",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
