# Generated by Django 4.0.5 on 2022-11-28 20:59

from django.db import migrations, models
import metering_billing.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0086_alter_invoicelineitem_quantity"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="metric",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="historicalmetric",
            name="metric_id",
            field=models.CharField(
                blank=True,
                default=metering_billing.utils.utils.metric_uuid,
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="historicalmetric",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("archived", "Archived")],
                default="active",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="metric",
            name="metric_id",
            field=models.CharField(
                blank=True,
                default=metering_billing.utils.utils.metric_uuid,
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="metric",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("archived", "Archived")],
                default="active",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmetric",
            name="billable_metric_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("archived", "Archived")], max_length=40
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="billable_metric_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("archived", "Archived")], max_length=40
            ),
        ),
    ]
