# Generated by Django 4.0.5 on 2022-11-28 21:00

import uuid

from django.db import migrations


def make_metric_ids_unique(apps, schema_editor):
    Metric = apps.get_model("metering_billing", "Metric")

    for metric in Metric.objects.all():
        metric.metric_id = str(uuid.uuid4())
        metric.save()


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0087_alter_metric_unique_together_and_more"),
    ]

    operations = [
        migrations.RunPython(make_metric_ids_unique),
    ]
