# Generated by Django 4.0.5 on 2022-11-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0084_auto_20221123_0606"),
        ("metering_billing", "0090_webhookendpoint_webhooktrigger_and_more"),
    ]

    operations = []
