# Generated by Django 4.0.5 on 2022-12-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0097_alter_subscriptionrecord_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalsubscriptionrecord",
            old_name="plan_version",
            new_name="billing_plan",
        ),
        migrations.RenameField(
            model_name="subscriptionrecord",
            old_name="plan_version",
            new_name="billing_plan",
        ),
    ]
