# Generated by Django 4.0.5 on 2022-12-05 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "metering_billing",
            "0098_rename_plan_version_historicalsubscriptionrecord_billing_plan_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsubscriptionrecord",
            name="flat_fee_already_billed",
        ),
        migrations.RemoveField(
            model_name="historicalsubscriptionrecord",
            name="prorated_flat_costs_dict",
        ),
        migrations.RemoveField(
            model_name="invoicelineitem",
            name="associated_plan_version",
        ),
        migrations.RemoveField(
            model_name="subscriptionrecord",
            name="flat_fee_already_billed",
        ),
        migrations.RemoveField(
            model_name="subscriptionrecord",
            name="prorated_flat_costs_dict",
        ),
        migrations.AddField(
            model_name="historicalsubscriptionrecord",
            name="flat_fee_behavior",
            field=models.CharField(
                choices=[
                    ("refund", "Refund"),
                    ("prorate", "Prorate"),
                    ("charge_full", "Charge Full"),
                ],
                default="prorate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalsubscriptionrecord",
            name="invoice_usage_charges",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="associated_subscription_record",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="metering_billing.subscription",
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="chargeable_item_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("usage_charge", "Usage Charge"),
                    ("recurring_charge", "Recurring Charge"),
                    ("one_time_charge", "One Time Charge"),
                    ("plan_adjustment", "Plan Adjustment"),
                    ("customer_adjustment", "Customer Adjustment"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrecord",
            name="flat_fee_behavior",
            field=models.CharField(
                choices=[
                    ("refund", "Refund"),
                    ("prorate", "Prorate"),
                    ("charge_full", "Charge Full"),
                ],
                default="prorate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrecord",
            name="invoice_usage_charges",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="metering_billing.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="metering_billing.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="billing_type",
            field=models.CharField(
                blank=True,
                choices=[("in_arrears", "In Arrears"), ("in_advance", "In Advance")],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="metering_billing.invoice",
            ),
        ),
    ]
