# Generated by Django 4.0.5 on 2022-12-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "metering_billing",
            "0100_remove_historicalsubscriptionrecord_scheduled_end_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubscriptionrecord",
            name="fully_billed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionrecord",
            name="fully_billed",
            field=models.BooleanField(default=False),
        ),
    ]
