# Generated by Django 4.0.5 on 2022-12-07 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0104_remove_historicalinvoice_invoice_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalinvoice",
            old_name="pricing_unit",
            new_name="currency",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="pricing_unit",
            new_name="currency",
        ),
    ]
