# Generated by Django 4.0.5 on 2022-12-10 01:53

from django.db import migrations, models
import metering_billing.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        (
            "metering_billing",
            "0107_rename_unadjusted_duration_days_historicalsubscriptionrecord_unadjusted_duration_seconds_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="idempotency_id",
            field=models.CharField(
                default=metering_billing.utils.utils.event_uuid, max_length=255
            ),
        ),
    ]
