# Generated by Django 4.0.5 on 2022-12-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0109_alter_event_idempotency_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="metric",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="metric",
            constraint=models.UniqueConstraint(
                fields=("organization", "metric_id"), name="unique_org_metric_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="metric",
            constraint=models.UniqueConstraint(
                fields=("organization", "billable_metric_name"),
                name="unique_org_billable_metric_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="metric",
            constraint=models.UniqueConstraint(
                fields=(
                    "organization",
                    "billable_metric_name",
                    "event_name",
                    "metric_type",
                    "usage_aggregation_type",
                    "billable_aggregation_type",
                    "property_name",
                    "granularity",
                    "is_cost_metric",
                ),
                name="unique_org_event_name_metric_type_and_other_fields",
            ),
        ),
    ]
