# Generated by Django 4.0.5 on 2022-12-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0110_alter_apitoken_name"),
        (
            "metering_billing",
            "0111_alter_customer_unique_together_customer_unique_email_and_more",
        ),
    ]

    operations = []
