# Generated by Django 4.0.5 on 2022-12-12 18:37

from django.db import migrations


def mark_as_demo(apps, schema_editor):
    Organization = apps.get_model("metering_billing", "Organization")
    Organization.objects.filter(company_name__startswith="demo_").update(is_demo=True)


class Migration(migrations.Migration):

    dependencies = [
        (
            "metering_billing",
            "0113_historicalorganization_is_demo_organization_is_demo_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(mark_as_demo, reverse_code=migrations.RunPython.noop),
    ]
