# Generated by Django 4.0.5 on 2022-12-13 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0115_event_inserted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtestsubstitution",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backtest_substitutions",
                to="metering_billing.organization",
            ),
        ),
        migrations.AddField(
            model_name="categoricalfilter",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorical_filters",
                to="metering_billing.organization",
            ),
        ),
        migrations.AddField(
            model_name="custompricingunitconversion",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_pricing_unit_conversions",
                to="metering_billing.organization",
            ),
        ),
        migrations.AddField(
            model_name="historicalbacktestsubstitution",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="metering_billing.organization",
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_line_items",
                to="metering_billing.organization",
            ),
        ),
        migrations.AddField(
            model_name="numericfilter",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="numeric_filters",
                to="metering_billing.organization",
            ),
        ),
        migrations.AddField(
            model_name="plancomponent",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_components",
                to="metering_billing.organization",
            ),
        ),
        migrations.AddField(
            model_name="pricetier",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_tiers",
                to="metering_billing.organization",
            ),
        ),
        migrations.AddField(
            model_name="webhooktrigger",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhook_triggers",
                to="metering_billing.organization",
            ),
        ),
    ]
