# Generated by Django 4.0.5 on 2022-12-13 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0117_auto_20221213_0529"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pricingunit",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="historicalorganization",
            name="currencies_provisioned",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="organization",
            name="currencies_provisioned",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="metering_billing.customer",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="metering_billing.organization",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="metering_billing.subscription",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricingunit",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="unique_code_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="pricingunit",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="unique_name_per_org"
            ),
        ),
    ]
