# Generated by Django 4.0.5 on 2022-12-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0123_auto_20221215_0520"),
    ]

    operations = [migrations.RenameModel("UsageEvent", "Event")]
