# Generated by Django 4.0.5 on 2022-12-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0126_alter_accountsreceivabletransaction_related_txns"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingunit",
            name="custom",
            field=models.BooleanField(default=False),
        ),
    ]
