# Generated by Django 4.0.5 on 2022-12-18 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0128_merge_20221215_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplan',
            name='display_version',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The currently active version of the plan. Customers that get signed up for this plan will be assigned this version.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='metering_billing.planversion'),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='parent_plan',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='If you are using our plan templating feature to create a new plan, this field will be set to the plan that you are using as a template.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='metering_billing.plan'),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='parent_product',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The product that this plan belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='metering_billing.product'),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='plan_duration',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], help_text='Duration of the plan', max_length=40),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='plan_name',
            field=models.CharField(help_text='Name of the plan', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='target_customer',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='If you are using our plan templating feature to create a new plan, this field will be set to the customer for which this plan is designed for. Keep in mind that this field and the parent_plan field are mutually necessary.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='metering_billing.customer'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='display_version',
            field=models.ForeignKey(blank=True, help_text='The currently active version of the plan. Customers that get signed up for this plan will be assigned this version.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='metering_billing.planversion'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='parent_plan',
            field=models.ForeignKey(blank=True, help_text='If you are using our plan templating feature to create a new plan, this field will be set to the plan that you are using as a template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_plans', to='metering_billing.plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='parent_product',
            field=models.ForeignKey(blank=True, help_text='The product that this plan belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_plans', to='metering_billing.product'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_duration',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], help_text='Duration of the plan', max_length=40),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(help_text='Name of the plan', max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='target_customer',
            field=models.ForeignKey(blank=True, help_text='If you are using our plan templating feature to create a new plan, this field will be set to the customer for which this plan is designed for. Keep in mind that this field and the parent_plan field are mutually necessary.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_plans', to='metering_billing.customer'),
        ),
        migrations.AlterField(
            model_name='pricingunit',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_units', to='metering_billing.organization'),
        ),
    ]
