# Generated by Django 4.0.5 on 2022-12-17 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0128_merge_20221215_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingunit',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_units', to='metering_billing.organization'),
        ),
    ]
