# Generated by Django 4.0.5 on 2022-12-19 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0129_alter_customer_customer_name_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmetric',
            name='event_name',
            field=models.CharField(help_text='Name of the event that this metric is tracking.', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='event_type',
            field=models.CharField(blank=True, choices=[('delta', 'Delta'), ('total', 'Total')], default='total', help_text="Used only for metrics of type 'continuous'. Please refer to our documentation for an explanation of the different types.", max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='granularity',
            field=models.CharField(blank=True, choices=[('seconds', 'Second'), ('minutes', 'Minute'), ('hours', 'Hour'), ('days', 'Day'), ('months', 'Month'), ('quarters', 'Quarter'), ('years', 'Year'), ('total', 'Total')], default='total', help_text="The granularity of the metric. Only applies to metrics of type 'continuous' or 'rate'.", max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='is_cost_metric',
            field=models.BooleanField(default=False, help_text='Whether or not this metric is a cost metric (used to track costs to your business).'),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='metric_type',
            field=models.CharField(choices=[('counter', 'Counter'), ('stateful', 'Stateful'), ('rate', 'Rate')], default='counter', help_text='The type of metric that this is. Please refer to our documentation for an explanation of the different types.', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='property_name',
            field=models.CharField(blank=True, help_text="The name of the property of the event that should be used for this metric. Doesn't apply if the metric is of type 'counter' with an aggregation of count.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='usage_aggregation_type',
            field=models.CharField(choices=[('count', 'Count'), ('sum', 'Sum'), ('max', 'Max'), ('unique', 'Unique'), ('latest', 'Latest'), ('average', 'Average')], default='count', help_text='The type of aggregation that should be used for this metric. Please refer to our documentation for an explanation of the different types.', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric',
            name='event_name',
            field=models.CharField(help_text='Name of the event that this metric is tracking.', max_length=50),
        ),
        migrations.AlterField(
            model_name='metric',
            name='event_type',
            field=models.CharField(blank=True, choices=[('delta', 'Delta'), ('total', 'Total')], default='total', help_text="Used only for metrics of type 'continuous'. Please refer to our documentation for an explanation of the different types.", max_length=20),
        ),
        migrations.AlterField(
            model_name='metric',
            name='granularity',
            field=models.CharField(blank=True, choices=[('seconds', 'Second'), ('minutes', 'Minute'), ('hours', 'Hour'), ('days', 'Day'), ('months', 'Month'), ('quarters', 'Quarter'), ('years', 'Year'), ('total', 'Total')], default='total', help_text="The granularity of the metric. Only applies to metrics of type 'continuous' or 'rate'.", max_length=10),
        ),
        migrations.AlterField(
            model_name='metric',
            name='is_cost_metric',
            field=models.BooleanField(default=False, help_text='Whether or not this metric is a cost metric (used to track costs to your business).'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='metric_type',
            field=models.CharField(choices=[('counter', 'Counter'), ('stateful', 'Stateful'), ('rate', 'Rate')], default='counter', help_text='The type of metric that this is. Please refer to our documentation for an explanation of the different types.', max_length=20),
        ),
        migrations.AlterField(
            model_name='metric',
            name='property_name',
            field=models.CharField(blank=True, help_text="The name of the property of the event that should be used for this metric. Doesn't apply if the metric is of type 'counter' with an aggregation of count.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='usage_aggregation_type',
            field=models.CharField(choices=[('count', 'Count'), ('sum', 'Sum'), ('max', 'Max'), ('unique', 'Unique'), ('latest', 'Latest'), ('average', 'Average')], default='count', help_text='The type of aggregation that should be used for this metric. Please refer to our documentation for an explanation of the different types.', max_length=10),
        ),
        migrations.AlterField(
            model_name='pricetier',
            name='range_end',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
