# Generated by Django 4.0.5 on 2022-12-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0130_remove_customer_unique_email_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("organization", "email"), name="unique_email"
            ),
        ),
    ]
