# Generated by Django 4.0.5 on 2022-12-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0130_alter_historicalmetric_event_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='metric',
            name='unique_org_billable_metric_name',
        ),
    ]
