# Generated by Django 4.0.5 on 2022-12-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0133_historicalorganization_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="proration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("seconds", "Second"),
                    ("minutes", "Minute"),
                    ("hours", "Hour"),
                    ("days", "Day"),
                    ("months", "Month"),
                    ("quarters", "Quarter"),
                    ("years", "Year"),
                    ("total", "Total"),
                ],
                default=None,
                help_text="The proration of the metric. Only applies to metrics of type 'continuous'.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalmetric",
            name="proration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("seconds", "Second"),
                    ("minutes", "Minute"),
                    ("hours", "Hour"),
                    ("days", "Day"),
                    ("months", "Month"),
                    ("quarters", "Quarter"),
                    ("years", "Year"),
                    ("total", "Total"),
                ],
                default=None,
                help_text="The proration of the metric. Only applies to metrics of type 'continuous'.",
                max_length=10,
                null=True,
            ),
        ),
    ]
