# Generated by Django 4.0.5 on 2022-12-31 17:24

from django.db import migrations


def transfer_component_granularity_to_metric(apps, schema_editor):
    PlanComponent = apps.get_model("metering_billing", "PlanComponent")
    Metric = apps.get_model("metering_billing", "Metric")
    for component in PlanComponent.objects.all():
        ass_metric = component.billable_metric
        if not ass_metric.proration:
            ass_metric.proration = component.proration_granularity
        ass_metric.save()


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0134_auto_20221231_1724"),
    ]

    operations = [
        migrations.RunPython(
            transfer_component_granularity_to_metric, migrations.RunPython.noop
        ),
    ]
