# Generated by Django 4.0.5 on 2023-01-04 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0135_auto_20221231_1724'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='metric',
            name='unique_org_event_name_metric_type_and_other_fields',
        ),
        migrations.RemoveField(
            model_name='plancomponent',
            name='proration_granularity',
        ),
        migrations.RemoveField(
            model_name='plancomponent',
            name='reset_frequency',
        ),
        migrations.RemoveField(
            model_name='plancomponent',
            name='separate_by',
        ),
        migrations.AddField(
            model_name='historicalmetric',
            name='custom_sql',
            field=models.TextField(blank=True, help_text='A custom SQL query that can be used to define the metric. Please refer to our documentation for more information.', null=True),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='subscription_filters_setting_provisioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalorganizationsetting',
            name='setting_values',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='metric',
            name='custom_sql',
            field=models.TextField(blank=True, help_text='A custom SQL query that can be used to define the metric. Please refer to our documentation for more information.', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_filters_setting_provisioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationsetting',
            name='setting_values',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(help_text='The primary email address of the customer, must be the same as the email address used to create the customer in the payment provider', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='email',
            field=models.EmailField(help_text='The primary email address of the customer, must be the same as the email address used to create the customer in the payment provider', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='event_type',
            field=models.CharField(blank=True, choices=[('delta', 'Delta'), ('total', 'Total')], help_text="Used only for metrics of type 'continuous'. Please refer to our documentation for an explanation of the different types.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='metric_type',
            field=models.CharField(choices=[('counter', 'Counter'), ('stateful', 'Stateful'), ('rate', 'Rate'), ('custom', 'Custom')], default='counter', help_text='The type of metric that this is. Please refer to our documentation for an explanation of the different types.', max_length=20),
        ),
        migrations.AlterField(
            model_name='metric',
            name='event_type',
            field=models.CharField(blank=True, choices=[('delta', 'Delta'), ('total', 'Total')], help_text="Used only for metrics of type 'continuous'. Please refer to our documentation for an explanation of the different types.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='metric_type',
            field=models.CharField(choices=[('counter', 'Counter'), ('stateful', 'Stateful'), ('rate', 'Rate'), ('custom', 'Custom')], default='counter', help_text='The type of metric that this is. Please refer to our documentation for an explanation of the different types.', max_length=20),
        ),
        migrations.AlterField(
            model_name='metric',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='metering_billing.organization'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('organization', 'billable_metric_name'), name='unique_org_billable_metric_name'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('billable_aggregation_type', 'billable_metric_name', 'custom_sql', 'event_name', 'granularity', 'is_cost_metric', 'metric_type', 'organization', 'property_name', 'usage_aggregation_type'), name='uq_metric_w_null__'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_metric_name__in', [None, '']), ('status', 'active')), fields=('billable_aggregation_type', 'custom_sql', 'event_name', 'granularity', 'is_cost_metric', 'metric_type', 'organization', 'property_name', 'usage_aggregation_type'), name='uq_metric_w_null__bi_me_na'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_aggregation_type__in', [None, '']), ('status', 'active')), fields=('billable_metric_name', 'custom_sql', 'event_name', 'granularity', 'is_cost_metric', 'metric_type', 'organization', 'property_name', 'usage_aggregation_type'), name='uq_metric_w_null__bi_ag_ty'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('property_name__in', [None, '']), ('status', 'active')), fields=('billable_aggregation_type', 'billable_metric_name', 'custom_sql', 'event_name', 'granularity', 'is_cost_metric', 'metric_type', 'organization', 'usage_aggregation_type'), name='uq_metric_w_null__pr_na'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('granularity__in', [None, '']), ('status', 'active')), fields=('billable_aggregation_type', 'billable_metric_name', 'custom_sql', 'event_name', 'is_cost_metric', 'metric_type', 'organization', 'property_name', 'usage_aggregation_type'), name='uq_metric_w_null__gr'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('custom_sql__in', [None, '']), ('status', 'active')), fields=('billable_aggregation_type', 'billable_metric_name', 'event_name', 'granularity', 'is_cost_metric', 'metric_type', 'organization', 'property_name', 'usage_aggregation_type'), name='uq_metric_w_null__cu_sq'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_aggregation_type__in', [None, '']), ('billable_metric_name__in', [None, '']), ('status', 'active')), fields=('custom_sql', 'event_name', 'granularity', 'is_cost_metric', 'metric_type', 'organization', 'property_name', 'usage_aggregation_type'), name='uq_metric_w_null__bi_ag_ty_bi_me_na'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_metric_name__in', [None, '']), ('property_name__in', [None, '']), ('status', 'active')), fields=('billable_aggregation_type', 'custom_sql', 'event_name', 'granularity', 'is_cost_metric', 'metric_type', 'organization', 'usage_aggregation_type'), name='uq_metric_w_null__bi_me_na_pr_na'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_metric_name__in', [None, '']), ('granularity__in', [None, '']), ('status', 'active')), fields=('billable_aggregation_type', 'custom_sql', 'event_name', 'is_cost_metric', 'metric_type', 'organization', 'property_name', 'usage_aggregation_type'), name='uq_metric_w_null__bi_me_na_gr'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_metric_name__in', [None, '']), ('custom_sql__in', [None, '']), ('status', 'active')), fields=('billable_aggregation_type', 'event_name', 'granularity', 'is_cost_metric', 'metric_type', 'organization', 'property_name', 'usage_aggregation_type'), name='uq_metric_w_null__bi_me_na_cu_sq'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_aggregation_type__in', [None, '']), ('property_name__in', [None, '']), ('status', 'active')), fields=('billable_metric_name', 'custom_sql', 'event_name', 'granularity', 'is_cost_metric', 'metric_type', 'organization', 'usage_aggregation_type'), name='uq_metric_w_null__bi_ag_ty_pr_na'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_aggregation_type__in', [None, '']), ('granularity__in', [None, '']), ('status', 'active')), fields=('billable_metric_name', 'custom_sql', 'event_name', 'is_cost_metric', 'metric_type', 'organization', 'property_name', 'usage_aggregation_type'), name='uq_metric_w_null__bi_ag_ty_gr'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_aggregation_type__in', [None, '']), ('custom_sql__in', [None, '']), ('status', 'active')), fields=('billable_metric_name', 'event_name', 'granularity', 'is_cost_metric', 'metric_type', 'organization', 'property_name', 'usage_aggregation_type'), name='uq_metric_w_null__bi_ag_ty_cu_sq'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('granularity__in', [None, '']), ('property_name__in', [None, '']), ('status', 'active')), fields=('billable_aggregation_type', 'billable_metric_name', 'custom_sql', 'event_name', 'is_cost_metric', 'metric_type', 'organization', 'usage_aggregation_type'), name='uq_metric_w_null__gr_pr_na'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('custom_sql__in', [None, '']), ('property_name__in', [None, '']), ('status', 'active')), fields=('billable_aggregation_type', 'billable_metric_name', 'event_name', 'granularity', 'is_cost_metric', 'metric_type', 'organization', 'usage_aggregation_type'), name='uq_metric_w_null__cu_sq_pr_na'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('custom_sql__in', [None, '']), ('granularity__in', [None, '']), ('status', 'active')), fields=('billable_aggregation_type', 'billable_metric_name', 'event_name', 'is_cost_metric', 'metric_type', 'organization', 'property_name', 'usage_aggregation_type'), name='uq_metric_w_null__cu_sq_gr'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_aggregation_type__in', [None, '']), ('billable_metric_name__in', [None, '']), ('property_name__in', [None, '']), ('status', 'active')), fields=('custom_sql', 'event_name', 'granularity', 'is_cost_metric', 'metric_type', 'organization', 'usage_aggregation_type'), name='uq_metric_w_null__bi_ag_ty_bi_me_na_pr_na'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_aggregation_type__in', [None, '']), ('billable_metric_name__in', [None, '']), ('granularity__in', [None, '']), ('status', 'active')), fields=('custom_sql', 'event_name', 'is_cost_metric', 'metric_type', 'organization', 'property_name', 'usage_aggregation_type'), name='uq_metric_w_null__bi_ag_ty_bi_me_na_gr'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_aggregation_type__in', [None, '']), ('billable_metric_name__in', [None, '']), ('custom_sql__in', [None, '']), ('status', 'active')), fields=('event_name', 'granularity', 'is_cost_metric', 'metric_type', 'organization', 'property_name', 'usage_aggregation_type'), name='uq_metric_w_null__bi_ag_ty_bi_me_na_cu_sq'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_metric_name__in', [None, '']), ('granularity__in', [None, '']), ('property_name__in', [None, '']), ('status', 'active')), fields=('billable_aggregation_type', 'custom_sql', 'event_name', 'is_cost_metric', 'metric_type', 'organization', 'usage_aggregation_type'), name='uq_metric_w_null__bi_me_na_gr_pr_na'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_metric_name__in', [None, '']), ('custom_sql__in', [None, '']), ('property_name__in', [None, '']), ('status', 'active')), fields=('billable_aggregation_type', 'event_name', 'granularity', 'is_cost_metric', 'metric_type', 'organization', 'usage_aggregation_type'), name='uq_metric_w_null__bi_me_na_cu_sq_pr_na'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_metric_name__in', [None, '']), ('custom_sql__in', [None, '']), ('granularity__in', [None, '']), ('status', 'active')), fields=('billable_aggregation_type', 'event_name', 'is_cost_metric', 'metric_type', 'organization', 'property_name', 'usage_aggregation_type'), name='uq_metric_w_null__bi_me_na_cu_sq_gr'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_aggregation_type__in', [None, '']), ('granularity__in', [None, '']), ('property_name__in', [None, '']), ('status', 'active')), fields=('billable_metric_name', 'custom_sql', 'event_name', 'is_cost_metric', 'metric_type', 'organization', 'usage_aggregation_type'), name='uq_metric_w_null__bi_ag_ty_gr_pr_na'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_aggregation_type__in', [None, '']), ('custom_sql__in', [None, '']), ('property_name__in', [None, '']), ('status', 'active')), fields=('billable_metric_name', 'event_name', 'granularity', 'is_cost_metric', 'metric_type', 'organization', 'usage_aggregation_type'), name='uq_metric_w_null__bi_ag_ty_cu_sq_pr_na'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_aggregation_type__in', [None, '']), ('custom_sql__in', [None, '']), ('granularity__in', [None, '']), ('status', 'active')), fields=('billable_metric_name', 'event_name', 'is_cost_metric', 'metric_type', 'organization', 'property_name', 'usage_aggregation_type'), name='uq_metric_w_null__bi_ag_ty_cu_sq_gr'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('custom_sql__in', [None, '']), ('granularity__in', [None, '']), ('property_name__in', [None, '']), ('status', 'active')), fields=('billable_aggregation_type', 'billable_metric_name', 'event_name', 'is_cost_metric', 'metric_type', 'organization', 'usage_aggregation_type'), name='uq_metric_w_null__cu_sq_gr_pr_na'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_aggregation_type__in', [None, '']), ('billable_metric_name__in', [None, '']), ('granularity__in', [None, '']), ('property_name__in', [None, '']), ('status', 'active')), fields=('custom_sql', 'event_name', 'is_cost_metric', 'metric_type', 'organization', 'usage_aggregation_type'), name='uq_metric_w_null__bi_ag_ty_bi_me_na_gr_pr_na'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_aggregation_type__in', [None, '']), ('billable_metric_name__in', [None, '']), ('custom_sql__in', [None, '']), ('property_name__in', [None, '']), ('status', 'active')), fields=('event_name', 'granularity', 'is_cost_metric', 'metric_type', 'organization', 'usage_aggregation_type'), name='uq_metric_w_null__bi_ag_ty_bi_me_na_cu_sq_pr_na'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_aggregation_type__in', [None, '']), ('billable_metric_name__in', [None, '']), ('custom_sql__in', [None, '']), ('granularity__in', [None, '']), ('status', 'active')), fields=('event_name', 'is_cost_metric', 'metric_type', 'organization', 'property_name', 'usage_aggregation_type'), name='uq_metric_w_null__bi_ag_ty_bi_me_na_cu_sq_gr'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_metric_name__in', [None, '']), ('custom_sql__in', [None, '']), ('granularity__in', [None, '']), ('property_name__in', [None, '']), ('status', 'active')), fields=('billable_aggregation_type', 'event_name', 'is_cost_metric', 'metric_type', 'organization', 'usage_aggregation_type'), name='uq_metric_w_null__bi_me_na_cu_sq_gr_pr_na'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_aggregation_type__in', [None, '']), ('custom_sql__in', [None, '']), ('granularity__in', [None, '']), ('property_name__in', [None, '']), ('status', 'active')), fields=('billable_metric_name', 'event_name', 'is_cost_metric', 'metric_type', 'organization', 'usage_aggregation_type'), name='uq_metric_w_null__bi_ag_ty_cu_sq_gr_pr_na'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(condition=models.Q(('billable_aggregation_type__in', [None, '']), ('billable_metric_name__in', [None, '']), ('custom_sql__in', [None, '']), ('granularity__in', [None, '']), ('property_name__in', [None, '']), ('status', 'active')), fields=('event_name', 'is_cost_metric', 'metric_type', 'organization', 'usage_aggregation_type'), name='uq_metric_w_null__bi_ag_ty_bi_me_na_cu_sq_gr_pr_na'),
        ),
    ]
