# Generated by Django 4.0.5 on 2023-01-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0141_team_teaminvitetoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmetric',
            name='event_type',
            field=models.CharField(blank=True, choices=[('delta', 'Delta'), ('total', 'Total')], help_text="Used only for metrics of type 'gauge'. Please refer to our documentation for an explanation of the different types.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='granularity',
            field=models.CharField(blank=True, choices=[('seconds', 'Second'), ('minutes', 'Minute'), ('hours', 'Hour'), ('days', 'Day'), ('months', 'Month'), ('quarters', 'Quarter'), ('years', 'Year'), ('total', 'Total')], default='total', help_text="The granularity of the metric. Only applies to metrics of type 'gauge' or 'rate'.", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='metric_type',
            field=models.CharField(choices=[('counter', 'Counter'), ('stateful', 'Stateful'), ('rate', 'Rate'), ('custom', 'Custom'), ('gauge', 'Gauge')], default='counter', help_text='The type of metric that this is. Please refer to our documentation for an explanation of the different types.', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='proration',
            field=models.CharField(blank=True, choices=[('seconds', 'Second'), ('minutes', 'Minute'), ('hours', 'Hour'), ('days', 'Day'), ('months', 'Month'), ('quarters', 'Quarter'), ('years', 'Year'), ('total', 'Total')], default=None, help_text="The proration of the metric. Only applies to metrics of type 'gauge'.", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='event_type',
            field=models.CharField(blank=True, choices=[('delta', 'Delta'), ('total', 'Total')], help_text="Used only for metrics of type 'gauge'. Please refer to our documentation for an explanation of the different types.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='granularity',
            field=models.CharField(blank=True, choices=[('seconds', 'Second'), ('minutes', 'Minute'), ('hours', 'Hour'), ('days', 'Day'), ('months', 'Month'), ('quarters', 'Quarter'), ('years', 'Year'), ('total', 'Total')], default='total', help_text="The granularity of the metric. Only applies to metrics of type 'gauge' or 'rate'.", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='metric_type',
            field=models.CharField(choices=[('counter', 'Counter'), ('stateful', 'Stateful'), ('rate', 'Rate'), ('custom', 'Custom'), ('gauge', 'Gauge')], default='counter', help_text='The type of metric that this is. Please refer to our documentation for an explanation of the different types.', max_length=20),
        ),
        migrations.AlterField(
            model_name='metric',
            name='proration',
            field=models.CharField(blank=True, choices=[('seconds', 'Second'), ('minutes', 'Minute'), ('hours', 'Hour'), ('days', 'Day'), ('months', 'Month'), ('quarters', 'Quarter'), ('years', 'Year'), ('total', 'Total')], default=None, help_text="The proration of the metric. Only applies to metrics of type 'gauge'.", max_length=10, null=True),
        ),
    ]
