# Generated by Django 4.0.5 on 2023-01-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0143_change_stateful_to_gauge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmetric",
            name="metric_type",
            field=models.CharField(
                choices=[
                    ("counter", "Counter"),
                    ("rate", "Rate"),
                    ("custom", "Custom"),
                    ("gauge", "Gauge"),
                ],
                default="counter",
                help_text="The type of metric that this is. Please refer to our documentation for an explanation of the different types.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="metric_type",
            field=models.CharField(
                choices=[
                    ("counter", "Counter"),
                    ("rate", "Rate"),
                    ("custom", "Custom"),
                    ("gauge", "Gauge"),
                ],
                default="counter",
                help_text="The type of metric that this is. Please refer to our documentation for an explanation of the different types.",
                max_length=20,
            ),
        ),
    ]
