# Generated by Django 4.0.5 on 2023-01-10 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0146_tag_plan_tags_tag_unique_with_tag_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorganization',
            old_name='company_name',
            new_name='organization_name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='company_name',
            new_name='organization_name',
        ),
    ]
