# Generated by Django 4.0.5 on 2023-01-10 19:20

from django.db import migrations, models
import metering_billing.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0147_rename_company_name_historicalorganization_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplan',
            name='created_on',
            field=models.DateTimeField(default=metering_billing.utils.utils.now_utc, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_on',
            field=models.DateTimeField(default=metering_billing.utils.utils.now_utc, null=True),
        ),
    ]
