# Generated by Django 4.0.5 on 2023-01-13 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0151_remove_historicalinvoice_payment_status_old_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorganization',
            old_name='organization_id',
            new_name='organization_id_old',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='organization_id',
            new_name='organization_id_old',
        ),
    ]
