# Generated by Django 4.0.5 on 2023-01-13 22:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0152_rename_organization_id_historicalorganization_organization_id_old_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='organization_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
