# Generated by Django 4.0.5 on 2023-01-13 22:41

from uuid import UUID

from django.db import migrations


def transfer_text_to_uuid(apps, schema_editor):
    Organization = apps.get_model("metering_billing", "Organization")
    for org in Organization.objects.all():
        uuid_string = org.organization_id_old.replace("org_", "")
        uuid_instance = UUID(uuid_string)
        org.organization_id = uuid_instance
        org.webhooks_provisioned = False
        org.save()


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0153_historicalorganization_organization_id_and_more"),
    ]

    operations = [
        migrations.RunPython(
            transfer_text_to_uuid, reverse_code=migrations.RunPython.noop
        ),
    ]
