# Generated by Django 4.0.5 on 2023-01-14 00:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0154_auto_20230113_2241"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalorganization",
            name="organization_id_old",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="organization_id_old",
        ),
        migrations.AlterField(
            model_name="historicalorganization",
            name="organization_id",
            field=models.UUIDField(
                default=uuid.uuid4, help_text="Unique identifier for the object."
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="organization_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique identifier for the object.",
                unique=True,
            ),
        ),
    ]
