# Generated by Django 4.0.5 on 2023-01-15 06:48

import uuid
from uuid import UUID

from django.db import migrations


def transfer_text_to_uuid(apps, schema_editor):
    Organization = apps.get_model("metering_billing", "Organization")
    for org in Organization.objects.all():
        org.organization_id = uuid.uuid4()
        org.save()

    Backtest = apps.get_model("metering_billing", "Backtest")
    for backtest in Backtest.objects.all():
        backtest.backtest_id = uuid.uuid4()
        backtest.save()

    CustomerBalanceAdjustment = apps.get_model(
        "metering_billing", "CustomerBalanceAdjustment"
    )
    for adjustment in CustomerBalanceAdjustment.objects.all():
        adjustment.adjustment_id = uuid.uuid4()
        adjustment.save()

    Feature = apps.get_model("metering_billing", "Feature")
    for feature in Feature.objects.all():
        feature.feature_id = uuid.uuid4()
        feature.save()

    Metric = apps.get_model("metering_billing", "Metric")
    for metric in Metric.objects.all():
        metric.metric_id = uuid.uuid4()
        metric.save()

    Invoice = apps.get_model("metering_billing", "Invoice")
    for invoice in Invoice.objects.all():
        invoice.invoice_id = uuid.uuid4()
        invoice.save()

    InvoiceLineItem = apps.get_model("metering_billing", "InvoiceLineItem")
    for line_item in InvoiceLineItem.objects.all():
        line_item.invoice_line_item_id = uuid.uuid4()
        line_item.save()

    OrganizationSetting = apps.get_model("metering_billing", "OrganizationSetting")
    for setting in OrganizationSetting.objects.all():
        setting.setting_id = uuid.uuid4()
        setting.save()

    Plan = apps.get_model("metering_billing", "Plan")
    for plan in Plan.objects.all():
        plan.plan_id = uuid.uuid4()
        plan.save()

    PlanVersion = apps.get_model("metering_billing", "PlanVersion")
    for plan_version in PlanVersion.objects.all():
        plan_version.version_id = uuid.uuid4()
        plan_version.save()

    Subscription = apps.get_model("metering_billing", "Subscription")
    for subscription in Subscription.objects.all():
        subscription.subscription_id = uuid.uuid4()
        subscription.save()

    SubscriptionRecord = apps.get_model("metering_billing", "SubscriptionRecord")
    for subscription_record in SubscriptionRecord.objects.all():
        subscription_record.subscription_record_id = uuid.uuid4()
        subscription_record.save()

    Tag = apps.get_model("metering_billing", "Tag")
    for tag in Tag.objects.all():
        tag.tag_id = uuid.uuid4()
        tag.save()

    UsageAlert = apps.get_model("metering_billing", "UsageAlert")
    for usage_alert in UsageAlert.objects.all():
        usage_alert.usage_alert_id = uuid.uuid4()
        usage_alert.save()

    WebhookEndpoint = apps.get_model("metering_billing", "WebhookEndpoint")
    for webhook in WebhookEndpoint.objects.all():
        webhook.webhook_endpoint_id = uuid.uuid4()
        webhook.webhook_secret = uuid.uuid4()
        webhook.save()


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0156_remove_planversion_unique_version_id_and_more"),
    ]

    operations = [
        migrations.RunPython(
            transfer_text_to_uuid, reverse_code=migrations.RunPython.noop
        ),
    ]
