# Generated by Django 4.0.5 on 2023-01-15 08:46

from django.db import migrations


def transfer_text_to_int(apps, schema_editor):
    PriceTier = apps.get_model("metering_billing", "PriceTier")
    for price_tier in PriceTier.objects.all():
        if price_tier.type_old == "flat":
            price_tier.type = 1
        elif price_tier.type_old == "per_unit":
            price_tier.type = 2
        elif price_tier.type_old == "free":
            price_tier.type = 3
        if price_tier.batch_rounding_type_old == "round_up":
            price_tier.batch_rounding_type = 1
        elif price_tier.batch_rounding_type_old == "round_down":
            price_tier.batch_rounding_type = 2
        elif price_tier.batch_rounding_type_old == "round_nearest":
            price_tier.batch_rounding_type = 3
        elif price_tier.batch_rounding_type_old == "no_rounding":
            price_tier.batch_rounding_type = 4
        price_tier.save()


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0160_pricetier_batch_rounding_type_pricetier_type"),
    ]

    operations = [
        migrations.RunPython(transfer_text_to_int, migrations.RunPython.noop),
    ]
