# Generated by Django 4.0.5 on 2023-01-22 21:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0164_alter_customer_default_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="team_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
