# Generated by Django 4.0.5 on 2023-01-23 01:27

import uuid

from django.db import migrations


def unique_team_id(apps, schema_editor):
    Team = apps.get_model("metering_billing", "Team")
    for team in Team.objects.all():
        team.team_id = uuid.uuid4()
        team.save()


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0165_team_team_id"),
    ]

    operations = [
        migrations.RunPython(unique_team_id, reverse_code=migrations.RunPython.noop),
    ]
