# Generated by Django 4.0.5 on 2023-01-23 01:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("metering_billing", "0166_team_id_populate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="team_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
