# Generated by Django 4.0.5 on 2023-01-23 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0167_alter_team_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplan',
            name='plan_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Base'), (2, 'Add-on')], default=1, help_text='The type of the plan: Base plan or add-on'),
        ),
        migrations.AddField(
            model_name='historicalsubscriptionrecord',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The parent subscription record.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='metering_billing.subscriptionrecord'),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Base'), (2, 'Add-on')], default=1, help_text='The type of the plan: Base plan or add-on'),
        ),
        migrations.AddField(
            model_name='subscriptionrecord',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent subscription record.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='metering_billing.subscriptionrecord'),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='plan_duration',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], help_text='Duration of the plan', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_duration',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], help_text='Duration of the plan', max_length=40, null=True),
        ),
    ]
