# Generated by Django 4.0.5 on 2023-02-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0170_historicalsubscriptionrecord_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='organization',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='metering_bi_organiz_af373b_idx',
        ),
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subscription',
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription_records',
            field=models.ManyToManyField(related_name='invoices', to='metering_billing.subscriptionrecord'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', '-issue_date'], name='metering_bi_organiz_943e95_idx'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
