# Generated by Django 4.0.5 on 2023-02-02 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0173_remove_historicalplanversion_flat_fee_billing_type_and_more'),
        ('metering_billing', '0174_remove_historicalsubscriptionrecord_unadjusted_duration_seconds_and_more'),
    ]

    operations = [
    ]
