# Generated by Django 4.0.5 on 2023-02-14 04:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0179_event_unique"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE UNIQUE INDEX metering_billing_usageevent_unique_idx ON metering_billing_usageevent (idempotency_id, organization_id)",
            reverse_sql="DROP INDEX metering_billing_usageevent_unique_idx",
        ),
    ]
