# Generated by Django 4.0.5 on 2023-02-14 04:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0179_event_unique"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE metering_billing_usageevent "
                "ADD CONSTRAINT usageevent_unique_organization_id_idempotency_id "
                "UNIQUE (organization_id, idempotency_id);"
            ),
            reverse_sql=(
                "ALTER TABLE metering_billing_usageevent "
                "DROP CONSTRAINT usageevent_unique_organization_id_idempotency_id;"
            ),
        ),
    ]
