# Generated by Django 4.0.5 on 2023-02-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0184_transfer_pp_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='integrations',
        ),
        migrations.RemoveField(
            model_name='historicalcustomer',
            name='integrations',
        ),
        migrations.RemoveField(
            model_name='historicalorganization',
            name='payment_provider_ids',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='payment_provider_ids',
        ),
    ]
