# Generated by Django 4.0.5 on 2023-02-17 21:03

from django.db import migrations, models

import metering_billing.models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0186_auto_20230217_2031"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="tax_provider",
        ),
        migrations.RemoveField(
            model_name="historicalcustomer",
            name="tax_provider",
        ),
        migrations.RemoveField(
            model_name="historicalorganization",
            name="tax_provider",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="tax_provider",
        ),
        migrations.AddField(
            model_name="customer",
            name="tax_providers",
            field=metering_billing.models.TaxProviderListField(default=[]),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="tax_providers",
            field=metering_billing.models.TaxProviderListField(default=[]),
        ),
        migrations.AddField(
            model_name="historicalorganization",
            name="tax_providers",
            field=metering_billing.models.TaxProviderListField(default=[2]),
        ),
        migrations.AddField(
            model_name="historicalplan",
            name="taxjar_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="tax_providers",
            field=metering_billing.models.TaxProviderListField(default=[2]),
        ),
        migrations.AddField(
            model_name="plan",
            name="taxjar_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
