# Generated by Django 4.0.5 on 2023-02-18 22:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0192_redo_metric_matviews"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE metering_billing_usageevent ALTER COLUMN cust_id TYPE TEXT;
            ALTER TABLE metering_billing_usageevent ALTER COLUMN event_name TYPE TEXT;
            ALTER TABLE metering_billing_usageevent ALTER COLUMN idempotency_id TYPE TEXT;
            ALTER TABLE metering_billing_usageevent DROP COLUMN customer_id;
            """,
            reverse_sql="""
            ALTER TABLE metering_billing_usageevent ADD COLUMN customer_id bigint;
            ALTER TABLE metering_billing_usageevent ALTER COLUMN idempotency_id TYPE varchar(255);
            ALTER TABLE metering_billing_usageevent ALTER COLUMN event_name TYPE varchar(100);
            ALTER TABLE metering_billing_usageevent ALTER COLUMN cust_id TYPE varchar(50);
            """,
        ),
    ]
