# Generated by Django 4.0.5 on 2023-02-18 22:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0192_redo_metric_matviews"),
    ]

    operations = []
