# Generated by Django 4.0.5 on 2023-02-18 22:12


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0193_auto_20230218_2202"),
    ]

    operations = [
        migrations.AddField(
            model_name="idempotencecheck",
            name="uuidv5_idempotency_id",
            field=models.UUIDField(null=True),
        ),
    ]
