# Generated by Django 4.0.5 on 2023-02-18 22:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "metering_billing",
            "0194_remove_idempotencecheck_unique_idempotency_id_per_org_raw_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION insert_event_with_idempotency_check() RETURNS trigger AS $$
                BEGIN
                    NEW.uuidv5_idempotency_id := uuid_generate_v5(
                        '904C0FFB-7005-414E-9B7D-8E3C5DDE266D'::uuid,
                        NEW.idempotency_id
                    );
                    INSERT INTO metering_billing_idempotencecheck (uuidv5_idempotency_id, time_created, organization_id)
                        VALUES (NEW.uuidv5_idempotency_id, NEW.time_created, NEW.organization_id);
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
            """,
        )
    ]
