# Generated by Django 4.0.5 on 2023-02-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0195_auto_20230218_2223'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='idempotencecheck',
            name='unique_idempotency_id_per_org_raw',
        ),
        migrations.RemoveField(
            model_name='idempotencecheck',
            name='idempotency_id',
        ),
        migrations.AlterField(
            model_name='idempotencecheck',
            name='uuidv5_idempotency_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='idempotencecheck',
            constraint=models.UniqueConstraint(fields=('organization', 'uuidv5_idempotency_id'), name='unique_hashed_idempotency_id_per_org_raw'),
        ),
    ]
