# Generated by Django 4.0.5 on 2023-02-19 06:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0197_trigger_on_customers"),
    ]

    operations = [
        migrations.RunSQL(
            """
            BEGIN;

            -- Modify columns to be non-nullable
            ALTER TABLE metering_billing_usageevent ALTER COLUMN uuidv5_customer_id SET NOT NULL;
            ALTER TABLE metering_billing_usageevent ALTER COLUMN uuidv5_event_name SET NOT NULL;
            ALTER TABLE metering_billing_usageevent ALTER COLUMN uuidv5_idempotency_id SET NOT NULL;

            -- Modify data types and drop column
            ALTER TABLE metering_billing_usageevent ALTER COLUMN uuidv5_customer_id TYPE TEXT;
            ALTER TABLE metering_billing_usageevent ALTER COLUMN uuidv5_event_name TYPE TEXT;
            ALTER TABLE metering_billing_usageevent ALTER COLUMN uuidv5_idempotency_id TYPE TEXT;
            ALTER TABLE metering_billing_usageevent DROP COLUMN customer_id;

            COMMIT;
            """,
            reverse_sql="""
            BEGIN;

            -- Add column and modify data types
            ALTER TABLE metering_billing_usageevent ADD COLUMN customer_id bigint;
            ALTER TABLE metering_billing_usageevent ALTER COLUMN uuidv5_idempotency_id TYPE varchar(255);
            ALTER TABLE metering_billing_usageevent ALTER COLUMN uuidv5_event_name TYPE varchar(100);
            ALTER TABLE metering_billing_usageevent ALTER COLUMN uuidv5_customer_id TYPE varchar(50);

            -- Modify columns to be nullable
            ALTER TABLE metering_billing_usageevent ALTER COLUMN uuidv5_customer_id DROP NOT NULL;
            ALTER TABLE metering_billing_usageevent ALTER COLUMN uuidv5_event_name DROP NOT NULL;
            ALTER TABLE metering_billing_usageevent ALTER COLUMN uuidv5_idempotency_id DROP NOT NULL;

            COMMIT;
            """,
        )
    ]
