# Generated by Django 4.0.5 on 2023-02-20 05:42

from django.db import migrations, models
import metering_billing.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0197_trigger_on_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.TextField(default=metering_billing.utils.utils.customer_uuid, help_text='The id provided when creating the customer, we suggest matching with your internal customer id in your backend', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='uuidv5_customer_id',
            field=models.UUIDField(help_text='The v5 UUID generated from the customer_id. This is used for efficient lookups in the database, specifically for the Events table', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='customer_id',
            field=models.TextField(default=metering_billing.utils.utils.customer_uuid, help_text='The id provided when creating the customer, we suggest matching with your internal customer id in your backend', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='uuidv5_customer_id',
            field=models.UUIDField(help_text='The v5 UUID generated from the customer_id. This is used for efficient lookups in the database, specifically for the Events table', null=True),
        ),
        migrations.AlterField(
            model_name='webhooktrigger',
            name='trigger_name',
            field=models.CharField(choices=[('invoice.created', 'invoice.created'), ('invoice.paid', 'invoice.paid'), ('usage_alert.triggered', 'usage_alert.triggered'), ('customer.created', 'customer.created')], max_length=40),
        ),
    ]
