# Generated by Django 4.0.5 on 2023-02-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0198_alter_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deleted',
            field=models.DateTimeField(help_text='The date the customer was deleted', null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='deleted',
            field=models.DateTimeField(help_text='The date the customer was deleted', null=True),
        ),
    ]
