# Generated by Django 4.0.5 on 2023-02-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0198_auto_20230219_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooktrigger',
            name='trigger_name',
            field=models.CharField(choices=[('invoice.created', 'invoice.created'), ('invoice.paid', 'invoice.paid'), ('usage_alert.triggered', 'usage_alert.triggered'), ('customer.created', 'customer.created')], max_length=40),
        ),
    ]
