# Generated by Django 4.0.5 on 2023-02-20 00:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0199_alter_webhooktrigger_trigger_name"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER update_historicalcustomer_uuid_trigger
                BEFORE INSERT OR UPDATE ON metering_billing_historicalcustomer
                FOR EACH ROW
                EXECUTE FUNCTION update_customer_uuid_function();
            """,
            reverse_sql="""
                DROP TRIGGER update_customer_uuid_trigger ON metering_billing_historicalcustomer;
            """,
        )
    ]
