# Generated by Django 4.0.5 on 2023-02-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0199_customer_deleted_historicalcustomer_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='invoice_past_due_webhook_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_past_due_webhook_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='webhooktrigger',
            name='trigger_name',
            field=models.CharField(choices=[('invoice.created', 'invoice.created'), ('invoice.paid', 'invoice.paid'), ('invoice.past_due', 'invoice.past_due'), ('usage_alert.triggered', 'usage_alert.triggered'), ('customer.created', 'customer.created')], max_length=40),
        ),
    ]
