# Generated by Django 4.0.5 on 2023-02-21 03:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "metering_billing",
            "0200_historicalinvoice_invoice_past_due_webhook_sent_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP TRIGGER IF EXISTS event_insert_trigger ON metering_billing_usageevent;
            DROP FUNCTION IF EXISTS insert_event_with_idempotency_check();
            """
        ),
    ]
