# Generated by Django 4.0.5 on 2023-02-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0202_auto_20230221_1857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldEvent',
        ),
    ]
