# Generated by Django 4.0.5 on 2023-02-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0203_delete_oldevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencecheck',
            name='time_created',
            field=models.DateTimeField(help_text='The time that the event occured, represented as a datetime in RFC3339 in the UTC timezome.'),
        ),
    ]
