# Generated by Django 4.0.5 on 2023-03-10 21:54

from decimal import Decimal

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0204_alter_idempotencecheck_time_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalinvoice",
            old_name="cost_due",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="cost_due",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="invoicelineitem",
            old_name="subtotal",
            new_name="base",
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="adjustments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(
                    default=dict,
                    help_text="Adjustment data. Must be a dict with keys: amount, account, adjustment_type.",
                ),
                blank=True,
                default=list,
                help_text="List of adjustments.",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="amount",
            field=models.DecimalField(
                decimal_places=10,
                default=Decimal("0"),
                help_text="Amount of the line item. This is the price after any adjustments are applied.",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="webhooktrigger",
            name="trigger_name",
            field=models.CharField(
                choices=[
                    ("customer.created", "customer.created"),
                    ("invoice.created", "invoice.created"),
                    ("invoice.paid", "invoice.paid"),
                    ("invoice.past_due", "invoice.past_due"),
                    ("subscription.created", "subscription.created"),
                    ("usage_alert.triggered", "usage_alert.triggered"),
                    ("subscription.cancelled", "subscription.cancelled"),
                ],
                max_length=40,
            ),
        ),
    ]
