# Generated by Django 4.0.5 on 2023-03-12 00:19

import uuid

import metering_billing.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0205_rename_cost_due_historicalinvoice_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="created",
            field=models.DateTimeField(default=metering_billing.utils.utils.now_utc),
        ),
        migrations.AddField(
            model_name="historicalcustomer",
            name="created",
            field=models.DateTimeField(default=metering_billing.utils.utils.now_utc),
        ),
        migrations.AddField(
            model_name="plancomponent",
            name="usage_component_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
            ),
        ),
        migrations.AddField(
            model_name="recurringcharge",
            name="recurring_charge_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
            ),
        ),
    ]
