# Generated by Django 4.0.5 on 2023-03-12 00:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0207_auto_20230312_0023"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plancomponent",
            name="usage_component_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="recurringcharge",
            name="recurring_charge_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
