# Generated by Django 4.0.5 on 2023-02-24 23:06

from django.db import migrations, models
import metering_billing.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0208_copy_addon_specs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalplan',
            name='addon_spec',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='addon_spec',
        ),
        migrations.AddField(
            model_name='historicalplan',
            name='not_active_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalplan',
            name='not_active_before',
            field=models.DateTimeField(blank=True, default=metering_billing.utils.utils.now_utc),
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='plans', to='metering_billing.feature'),
        ),
        migrations.AddField(
            model_name='plan',
            name='metrics',
            field=models.ManyToManyField(blank=True, related_name='plans', to='metering_billing.metric'),
        ),
        migrations.AddField(
            model_name='plan',
            name='not_active_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='not_active_before',
            field=models.DateTimeField(blank=True, default=metering_billing.utils.utils.now_utc),
        ),
        migrations.AddField(
            model_name='planversion',
            name='not_active_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planversion',
            name='not_active_before',
            field=models.DateTimeField(blank=True, default=metering_billing.utils.utils.now_utc),
        ),
    ]
