# Generated by Django 4.0.5 on 2023-02-24 23:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0213_auto_20230224_2336"),
    ]

    operations = []
