# Generated by Django 4.0.5 on 2023-02-25 23:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0215_remove_planversion_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="planversion",
            old_name="pricing_unit",
            new_name="currency",
        ),
    ]
