# Generated by Django 4.0.5 on 2023-02-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0215_remove_planversion_description_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plan',
            name='both_null_or_both_not_null',
        ),
        migrations.RenameField(
            model_name='planversion',
            old_name='pricing_unit',
            new_name='currency',
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(check=models.Q(('is_addon', True), ('plan_duration__isnull', False), _connector='OR'), name='addon_cant_have_duration'),
        ),
    ]
