# Generated by Django 4.0.5 on 2023-02-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0216_remove_plan_both_null_or_both_not_null_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubscriptionrecord',
            name='last_billing_date',
        ),
        migrations.RemoveField(
            model_name='historicalsubscriptionrecord',
            name='next_billing_date',
        ),
        migrations.RemoveField(
            model_name='planversion',
            name='version',
        ),
        migrations.RemoveField(
            model_name='subscriptionrecord',
            name='last_billing_date',
        ),
        migrations.RemoveField(
            model_name='subscriptionrecord',
            name='next_billing_date',
        ),
    ]
