# Generated by Django 4.0.5 on 2023-03-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0222_auto_20230302_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubscriptionrecord',
            name='fully_billed',
        ),
        migrations.RemoveField(
            model_name='historicalsubscriptionrecord',
            name='unadjusted_duration_microseconds',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='associated_plan_component',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='associated_recurring_charge',
        ),
        migrations.RemoveField(
            model_name='subscriptionrecord',
            name='fully_billed',
        ),
        migrations.RemoveField(
            model_name='subscriptionrecord',
            name='unadjusted_duration_microseconds',
        ),
    ]
