# Generated by Django 4.0.5 on 2023-03-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0222_auto_20230302_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='associated_plan_component',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='associated_recurring_charge',
        ),
    ]
