# Generated by Django 4.0.5 on 2023-03-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0223_remove_invoicelineitem_associated_plan_component_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubscriptionrecord',
            name='fully_billed',
        ),
        migrations.RemoveField(
            model_name='historicalsubscriptionrecord',
            name='unadjusted_duration_microseconds',
        ),
        migrations.RemoveField(
            model_name='subscriptionrecord',
            name='fully_billed',
        ),
        migrations.RemoveField(
            model_name='subscriptionrecord',
            name='unadjusted_duration_microseconds',
        ),
    ]
