# Generated by Django 4.0.5 on 2023-03-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0225_remove_recurringcharge_plan_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscriptionrecord',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscriptionrecord',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
