# Generated by Django 4.0.5 on 2023-03-15 03:42

from django.db import migrations


def fill_null_pricing_unit_in(apps, schema_editor):
    RecurringCharge = apps.get_model("metering_billing", "RecurringCharge")

    for recurring_charge in RecurringCharge.objects.filter(pricing_unit__isnull=True):
        recurring_charge.pricing_unit = recurring_charge.plan_version.currency
        recurring_charge.save()


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0227_merge_20230314_0709"),
    ]

    operations = [
        migrations.RunPython(fill_null_pricing_unit_in),
    ]
