# Generated by Django 4.0.5 on 2023-03-16 00:22

from django.db import migrations, models
import django.db.models.deletion
import metering_billing.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0228_auto_20230315_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='crm_integration_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='webhooktrigger',
            name='trigger_name',
            field=models.CharField(choices=[('customer.created', 'customer.created'), ('invoice.created', 'invoice.created'), ('invoice.paid', 'invoice.paid'), ('invoice.past_due', 'invoice.past_due'), ('subscription.created', 'subscription.created'), ('usage_alert.triggered', 'usage_alert.triggered'), ('subscription.cancelled', 'subscription.cancelled'), ('subscription.renewed', 'subscription.renewed')], max_length=40),
        ),
        migrations.CreateModel(
            name='UnifiedCRMOrganizationIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_type', models.IntegerField(choices=[(1, 'salesforce')])),
                ('access_token', models.TextField()),
                ('native_org_url', models.TextField()),
                ('native_org_id', models.TextField()),
                ('connection_id', models.TextField()),
                ('created', models.DateTimeField(default=metering_billing.utils.utils.now_utc)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_crm_organization_links', to='metering_billing.organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='unifiedcrmorganizationintegration',
            constraint=models.UniqueConstraint(fields=('organization', 'crm_type'), name='unique_crm_type'),
        ),
    ]
