# Generated by Django 4.0.5 on 2023-03-20 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0229_historicalorganization_crm_settings_provisioned_and_more'),
        ('metering_billing', '0231_remove_subscriptionrecord_filters'),
    ]

    operations = [
    ]
