# Generated by Django 4.0.5 on 2023-03-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0232_merge_20230320_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='external_payment_obj_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='external_payment_obj_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
