# Generated by Django 4.0.5 on 2023-03-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering_billing', '0233_historicalinvoice_external_payment_obj_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancomponent',
            name='bulk_pricing_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
