# Generated by Django 4.0.5 on 2023-03-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metering_billing", "0240_auto_20230324_2158"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorganization",
            name="payment_grace_period",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="payment_grace_period",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name="OrganizationSetting",
        ),
    ]
