/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Address {
  /** City, district, suburb, town, or village */
  city: string;
  /** ISO 3166-1 alpha-2 country code */
  country: string;
  /** Address line 1 (e.g., street, PO Box, or company name) */
  line1: string;
  /** Address line 2 (e.g., apartment, suite, unit, or building) */
  line2?: string;
  /** ZIP or postal code */
  postalCode: string;
  /** State, county, province, or region */
  state: string;
}
