/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LotusApi } from "../../../..";

export interface Customer {
  customerId: string;
  email: string;
  customerName: string;
  invoices: LotusApi.LightweightInvoice[];
  totalAmountDue: number;
  subscriptions: LotusApi.SubscriptionRecord[];
  /**
   * A dictionary containing the customer's integrations. Keys are the integration type, and the value is a dictionary containing the integration's properties, which can vary by integration.
   *
   */
  integration: LotusApi.CustomerIntegrations;
  defaultCurrency: LotusApi.PricingUnit;
  paymentProvider?: LotusApi.PaymentProvider;
  hasPaymentMethod: boolean;
  address?: LotusApi.Address;
  /** Tax rate as percentage. For example, 10.5 for 10.5% */
  taxRate: number;
}
