/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface LightweightCustomer {
  /** The display name of the customer */
  customerName?: string;
  /** The primary email address of the customer, must be the same as the email address used to create the customer in the payment provider */
  email?: string;
  /** The id provided when creating the customer, we suggest matching with your internal customer id in your backend */
  customerId: string;
}
