/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LotusApi } from "../../../..";

export interface LightweightInvoice {
  currency: LotusApi.PricingUnit;
  externalPaymentObjId?: string;
  seller: LotusApi.Seller;
  invoiceId: string;
  endDate: string;
  invoiceNumber: string;
  costDue: number;
  dueDate?: string;
  paymentStatus: LotusApi.PaymentStatus;
  invoicePdf?: string;
  startDate: string;
  issueDate: string;
  externalPaymentObjType?: LotusApi.PaymentProvider;
}
