/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PaymentStatus = "paid" | "unpaid";

export const PaymentStatus = {
  Paid: "paid",
  Unpaid: "unpaid",
} as const;
