/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LotusApi } from "../../../..";

export interface Seller {
  name: string;
  address?: LotusApi.Address;
  phone?: string;
  email?: string;
}
