/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LotusApi } from "../../../..";

export interface SubscriptionRecord {
  /** The time the subscription starts. This will be a string in yyyy-mm-dd HH:mm:ss format in UTC time. */
  startDate: string;
  /** The time the subscription starts. This will be a string in yyyy-mm-dd HH:mm:ss format in UTC time. */
  endDate: string;
  /** Whether the subscription automatically renews. Defaults to true. */
  autoRenew: boolean;
  /** Whether this subscription came from a renewal or from a first-time. Defaults to true on creation. */
  isNew: boolean;
  subscriptionFilters: LotusApi.SubscriptionCategoricalFilter[];
  customer: LotusApi.LightweightCustomer;
  billingPlan: LotusApi.LightweightPlanVersion;
  /** Whether the subscription has been fully billed and finalized. */
  fullyBilled: boolean;
}
