/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const LotusApiEnvironment = {
  Cloud: "https://api.uselotus.io",
  Local: "http://localhost:8000",
} as const;

export type LotusApiEnvironment =
  | typeof LotusApiEnvironment.Cloud
  | typeof LotusApiEnvironment.Local;
