/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LotusApi } from "../../../..";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
  serializers.apiTokens.list.Response.Raw,
  LotusApi.ApiToken[]
> = core.serialization.list(
  core.serialization.lazyObject(async () => (await import("../../..")).ApiToken)
);

export declare namespace Response {
  type Raw = serializers.ApiToken.Raw[];
}
