# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Django/Postgres CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies with pipenv
      run: |
        pip install pipenv
        pipenv install --deploy --dev

    - name: Migrations
      env:
        PIPENV_NOSPIN: 'true'
        WORKON_HOME: ~/.pipenv/virtualenvs
        REDIS_HOST: localhost
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}
        DATABASE_URL: 'postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/test_db'
        DJANGO_SECRET_KEY: 'KEY'
        DJANGO_SETTINGS_MODULE: CONFIG'
        PYTHONPATH: '.'
        DJANGO_DEBUG: 'False'
      run: |
        pipenv run python manage.py migrate --noinput

    - name: Tests
      env:
        PIPENV_NOSPIN: 'true'
        WORKON_HOME: ~/.pipenv/virtualenvs
        REDIS_HOST: localhost
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}
        DATABASE_URL: 'postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/test_db'
        DJANGO_SECRET_KEY: 'KEY'
        DJANGO_SETTINGS_MODULE: CONFIG'
        PYTHONPATH: '.'
        DJANGO_DEBUG: 'False'
      run: |
        pipenv run python manage.py test 

    - name: Codestyle
      env:
        PIPENV_NOSPIN: 'true'
        WORKON_HOME: ~/.pipenv/virtualenvs
        REDIS_HOST: localhost
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}
        DATABASE_URL: 'postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/test_db'
        DJANGO_SECRET_KEY: 'KEY'
        DJANGO_SETTINGS_MODULE: CONFIG'
        PYTHONPATH: '.'
        DJANGO_DEBUG: 'False'
      run: |
        pipenv run black --check .