name: Lint and Prettier

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: frontend
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn

      # - name: Lint with ESLint
      #   run: yarn lint
      - name: Run Prettier
        run: pwd && yarn pretty
